_: just-choose

set dotenv-load := false

just-choose:
    #!/usr/bin/env sh
    choose_recipe=$(just --summary | tr ' ' '\n' | /usr/local/opt/choose-gui/bin/choose)
    echo "Choose Recipe: ${choose_recipe}"
    just "${choose_recipe}"

just-list:
    just --list

# Basic : 1 : Git Clone
git-clone-basic:
    git clone https://github.com/yiisoft/yii2-app-basic root

# Basic : 2.1 : Composer Update
composer-update:
    cd ./root && composer update

# Basic : 2.2 : Patch
patch:
    cd ./root && composer require fakerphp/faker:1.13.0 # < v1.14.0

# Basic : 3 : Composer Install
composer-install:
    cd ./root && composer install

# Basic : 4 : Serve
serve-basic:
    cd ./root && php yii serve

# Basic : 5 : Open
open-basic:
    open 'http://localhost:8080/'

# Basic : 6 : Open Code by PhpStorm
phpstorm-basic:
    open -a "PhpStorm" ./root

# Basic : Files
files:
    cd ./root && \
        fd --hidden --no-ignore --full-path '.' \
            --exclude '/.git/' \
            --exclude '/.github/' \
            --exclude '/tests/' \
            --exclude '/vagrant/' \
            --exclude '/.gitattributes' \
            --exclude '/.gitignore' \
            --exclude '/LICENSE.md' \
            --exclude '/README.md' \
            --exclude '/Vagrantfile' \
            --exclude '/codeception.yml' \
            --exclude '/docker-compose.yml'

# Basic : Clean
clean-basic:
    trash ./root
