_: just-choose

just-choose:
    #!/usr/bin/env sh
    choose_recipe=$(just --summary | tr ' ' '\n' | /usr/local/opt/choose-gui/bin/choose)
    echo "Choose Recipe: ${choose_recipe}"
    just "${choose_recipe}"

just-list:
    just --list

# Yii Template : 1 : Git Clone
git-clone-template:
    git clone https://github.com/huzhenghui/yii-template-basic-1 root

# Yii Template : 2 : Composer Update
composer-update:
    cd ./root && composer update

# Yii Template : 3 : Composer Install
composer-install:
    cd ./root && composer install

# Yii Template : 4 : Serve
serve-template:
    cd ./root && php yii serve

# Yii Template : 5 : Open
open-template:
    open 'http://localhost:8080/'

# Yii Template : 6 : Open Code by PhpStorm
phpstorm-template:
    open -a "PhpStorm" ./root

# Yii Template : Clean
clean-template:
    trash ./root
