_: just-choose

just-choose:
    #!/usr/bin/env sh
    choose_recipe=$(just --summary | tr ' ' '\n' | /usr/local/opt/choose-gui/bin/choose)
    echo "Choose Recipe: ${choose_recipe}"
    just "${choose_recipe}"

just-list:
    just --list

# Basic : 1 : Create Project by Composer
create-project-basic:
    composer create-project --prefer-dist yiisoft/yii2-app-basic ./root

# Basic : 2 : Serve
serve-basic:
    cd ./root && php yii serve

# Basic : 3 : Open
open-basic:
    open 'http://localhost:8080/'

# Basic : 4 : Open Code by PhpStorm
phpstorm-basic:
    open -a "PhpStorm" ./root

# Basic : Yii Help
help-basic-yii:
    cd ./root && php yii help

# Basic : Yii Help Serve
help-basic-yii-serve:
    cd ./root && php yii help serve

# Basic : Clean
clean-basic:
    trash ./root
